version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directory: "/server"
    schedule:
      interval: "monthly"
